# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.canzanese.com" # the base hostname & protocol for your site

plugins: ['jekyll-paginate', 'jekyll-twitter-plugin', 'jekyll/scholar']

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: Ray Canzanese
  avatar: assets/img/avatar.png
  gravatar: # email md5 hash
  description: "Teaching, Research, Projects, and Musings of Ray Canzanese" # used by search engines
  
  # Header and footer text
  header_text:
  footer_text: >
   Powered by <a href="http://jekyllrb.com">Jekyll</a> with <a href="https://rohanchandra.github.io/project/type/">Type Theme</a> and <a href="https://github.com/inukshuk/jekyll-scholar">Jekyll-Scholar</a>.

  avatar: assets/img/avatar.png
  favicon: assets/favicon.ico

  # Icons
  rss: false
  email_address: # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket: 
  dribbble: 
  facebook: "rcanzanese"
  flickr: 
  geocaching: "97be5aa9-4122-426c-aca5-11fed0a469b5"
  github: "rcanzanese"
  google_plus: 
  instagram: 
  linkedin:  "https://www.linkedin.com/pub/raymond-canzanese-jr/6/a84/178" # full URL
  pinterest: 
  reddit: 
  soundcloud: 
  stack_exchange:  # full URL
  steam: 
  tumblr: 
  twitter: "ray_canzanese"
  wordpress: 
  youtube: 
  
  # Scripts
  google_analytics: "UA-40099975-1" # tracking id, e.g. "UA-000000-01"
  disqus_shortname: "canzanese"
  
  katex: true # Enable if using math markup
  search: false # Enable the search feature

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next_post: "Next post"
  str_previous_post: "Previous post"
  str_next_page: "Next"
  str_previous_page: "Prev"
  str_continue_reading: "Continue reading"
  str_javascript_required_disqus: "Please enable JavaScript to view comments."
  str_search_no_results: "No results found."

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: false

# PAGINATION
paginate: 10
paginate_path: "archive/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
  
# BIBTEX SETTINGS
scholar:
  style:  _bibliography/ieee_custom
  locale: en
  sort_by: year
  order: descending
  source: ./_bibliography
  bibliography: "*.bib"
  bibliography_template: bib
  replace_strings: true
  join_strings:    true
  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:  "[bib]"
  query: "@*"
  repository: ./publications/
  
exclude:
  - Gemfile
  - Gemfile.lock
