# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.canzanese.com" # the base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION
theme:
  # Meta
  title: Ray Canzanese
  avatar: avatar.png
  gravatar: # email md5 hash
  description: "Teaching, Research, Projects, and Musings of Ray Canzanese" # used by search engines
  
  # Header and footer text
  header_text:
  footer_text: >
   Powered by <a href="http://jekyllrb.com">Jekyll</a> with <a href="https://rohanchandra.github.io/project/type/">Type Theme</a> and <a href="https://github.com/inukshuk/jekyll-scholar">Jekyll-Scholar</a>.
  
  # Icons
  rss: false
  email_address: # full email address, e.g. "sam@example.com"
  behance:
  bitbucket: 
  dribbble: 
  facebook: "rcanzanese"
  flickr: 
  github: "rcanzanese"
  google_plus: 
  instagram: 
  linkedin:  "https://www.linkedin.com/pub/raymond-canzanese-jr/6/a84/178" # full URL
  pinterest: 
  reddit: 
  soundcloud: 
  stack_exchange:  # full URL
  steam: 
  tumblr: 
  twitter:
  wordpress: 
  youtube: 
  
  # Scripts
  google_analytics: "UA-40099975-1" # tracking id, e.g. "UA-000000-01"
  disqus_shortname: "canzanese"
  
  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue reading"
  
  # Colors, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"

# PAGINATION
paginate: 10
paginate_path: "archive/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: :compressed
  
# BIBTEX SETTINGS
scholar:
  style:  _bibliography/ieee_custom
  locale: en
  sort_by: year
  order: descending
  source: ./_bibliography
  bibliography: other.bib
  bibliography_template: bib
  replace_strings: true
  join_strings:    true
  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details
  query: "@*"
  repository: ./publications/
  
